/** 100 corporate clothing products with GHS currency and inStock */
export const Products = [
  // -------------------- Suits (1-10) --------------------
  {
    id: 1,
    name: "Classic Black Suit",
    category: "Suits",
    price: 199.99,
    currency: "GHS",
    image: "/images/suits/black-suit.jpg",
    description: "Elegant black suit for formal business occasions",
    inStock: true,
  },
  {
    id: 2,
    product_name: "Navy Blue Suit",
    category: "Suits",
    price: 219.99,
    currency: "GHS",
    image_url: "/images/suits/navy-suit.jpg",
    description: "Professional navy suit with slim fit design",
    inStock: true,
  },
  {
    id: 3,
    name: "Charcoal Grey Suit",
    category: "Suits",
    price: 209.99,
    currency: "GHS",
    image: "/images/suits/grey-suit.jpg",
    description: "Modern grey suit for office or meetings",
    inStock: false,
  },
  {
    id: 4,
    name: "Pinstripe Suit",
    category: "Suits",
    price: 229.99,
    currency: "GHS",
    image: "/images/suits/pinstripe-suit.jpg",
    description: "Classic pinstripe design for a professional look",
    inStock: true,
  },
  {
    id: 5,
    name: "Slim Fit Black Suit",
    category: "Suits",
    price: 199.99,
    currency: "GHS",
    image: "/images/suits/slim-black.jpg",
    description: "Tailored slim fit black suit",
    inStock: true,
  },
  {
    id: 6,
    name: "Two-Piece Navy Suit",
    category: "Suits",
    price: 219.99,
    currency: "GHS",
    image: "/images/suits/navy-two-piece.jpg",
    description: "Elegant two-piece suit",
    inStock: true,
  },
  {
    id: 7,
    name: "Grey Business Suit",
    category: "Suits",
    price: 205.99,
    currency: "GHS",
    image: "/images/suits/grey-business.jpg",
    description: "Stylish grey suit for office wear",
    inStock: true,
  },
  {
    id: 8,
    name: "Blue Striped Suit",
    category: "Suits",
    price: 225.99,
    currency: "GHS",
    image: "/images/suits/blue-striped.jpg",
    description: "Subtle stripe for modern look",
    inStock: false,
  },
  {
    id: 9,
    name: "Formal Black Tuxedo",
    category: "Suits",
    price: 299.99,
    currency: "GHS",
    image: "/images/suits/black-tuxedo.jpg",
    description: "Tuxedo for corporate evening events",
    inStock: true,
  },
  {
    id: 10,
    name: "Light Grey Suit",
    category: "Suits",
    price: 215.99,
    currency: "GHS",
    image: "/images/suits/light-grey.jpg",
    description: "Professional light grey suit",
    inStock: true,
  },

  // -------------------- Shirts (11-20) --------------------
  {
    id: 11,
    name: "White Dress Shirt",
    category: "Shirts",
    price: 49.99,
    currency: "GHS",
    image: "/images/shirts/white-shirt.jpg",
    description: "Crisp white shirt for office meetings",
    inStock: true,
  },
  {
    id: 12,
    name: "Light Blue Formal Shirt",
    category: "Shirts",
    price: 44.99,
    currency: "GHS",
    image: "/images/shirts/blue-shirt.jpg",
    description: "Comfortable light blue shirt",
    inStock: true,
  },
  {
    id: 13,
    name: "Striped Dress Shirt",
    category: "Shirts",
    price: 52.99,
    currency: "GHS",
    image: "/images/shirts/striped-shirt.jpg",
    description: "White shirt with subtle stripes",
    inStock: false,
  },
  {
    id: 14,
    name: "Pink Office Shirt",
    category: "Shirts",
    price: 47.99,
    currency: "GHS",
    image: "/images/shirts/pink-shirt.jpg",
    description: "Professional pastel pink shirt",
    inStock: true,
  },
  {
    id: 15,
    name: "Grey Formal Shirt",
    category: "Shirts",
    price: 46.99,
    currency: "GHS",
    image: "/images/shirts/grey-shirt.jpg",
    description: "Classic grey shirt for corporate wear",
    inStock: true,
  },
  {
    id: 16,
    name: "Black Slim Fit Shirt",
    category: "Shirts",
    price: 49.99,
    currency: "GHS",
    image: "/images/shirts/black-shirt.jpg",
    description: "Slim fit black shirt for office events",
    inStock: true,
  },
  {
    id: 17,
    name: "Light Green Shirt",
    category: "Shirts",
    price: 45.99,
    currency: "GHS",
    image: "/images/shirts/green-shirt.jpg",
    description: "Professional light green shirt",
    inStock: false,
  },
  {
    id: 18,
    name: "Lavender Shirt",
    category: "Shirts",
    price: 48.99,
    currency: "GHS",
    image: "/images/shirts/lavender-shirt.jpg",
    description: "Soft lavender office shirt",
    inStock: true,
  },
  {
    id: 19,
    name: "White Short Sleeve Shirt",
    category: "Shirts",
    price: 42.99,
    currency: "GHS",
    image: "/images/shirts/white-short.jpg",
    description: "Casual office short sleeve shirt",
    inStock: true,
  },
  {
    id: 20,
    name: "Blue Checked Shirt",
    category: "Shirts",
    price: 50.99,
    currency: "GHS",
    image: "/images/shirts/blue-checked.jpg",
    description: "Modern checked shirt for office",
    inStock: true,
  },

  // -------------------- Trousers (21-30) --------------------
  {
    id: 21,
    name: "Black Office Trousers",
    category: "Trousers",
    price: 59.99,
    currency: "GHS",
    image: "/images/trousers/black-trousers.jpg",
    description: "Slim fit black trousers",
    inStock: true,
  },
  {
    id: 22,
    name: "Grey Formal Pants",
    category: "Trousers",
    price: 54.99,
    currency: "GHS",
    image: "/images/trousers/grey-trousers.jpg",
    description: "Comfortable grey pants",
    inStock: true,
  },
  {
    id: 23,
    name: "Navy Dress Pants",
    category: "Trousers",
    price: 57.99,
    currency: "GHS",
    image: "/images/trousers/navy-trousers.jpg",
    description: "Professional navy trousers",
    inStock: false,
  },
  {
    id: 24,
    name: "Charcoal Slim Pants",
    category: "Trousers",
    price: 56.99,
    currency: "GHS",
    image: "/images/trousers/charcoal-slim.jpg",
    description: "Slim fit grey pants",
    inStock: true,
  },
  {
    id: 25,
    name: "Beige Office Trousers",
    category: "Trousers",
    price: 53.99,
    currency: "GHS",
    image: "/images/trousers/beige-trousers.jpg",
    description: "Light beige trousers",
    inStock: true,
  },
  {
    id: 26,
    name: "Black Slim Fit Pants",
    category: "Trousers",
    price: 58.99,
    currency: "GHS",
    image: "/images/trousers/slim-black.jpg",
    description: "Slim fit black formal pants",
    inStock: true,
  },
  {
    id: 27,
    name: "Grey Wool Pants",
    category: "Trousers",
    price: 62.99,
    currency: "GHS",
    image: "/images/trousers/wool-grey.jpg",
    description: "Warm wool trousers for winter office",
    inStock: false,
  },
  {
    id: 28,
    name: "Light Grey Pants",
    category: "Trousers",
    price: 55.99,
    currency: "GHS",
    image: "/images/trousers/light-grey.jpg",
    description: "Professional light grey pants",
    inStock: true,
  },
  {
    id: 29,
    name: "Blue Formal Pants",
    category: "Trousers",
    price: 56.99,
    currency: "GHS",
    image: "/images/trousers/blue-formal.jpg",
    description: "Elegant blue trousers for office",
    inStock: true,
  },
  {
    id: 30,
    name: "Charcoal Classic Pants",
    category: "Trousers",
    price: 54.99,
    currency: "GHS",
    image: "/images/trousers/charcoal-classic.jpg",
    description: "Classic charcoal pants",
    inStock: true,
  },

  // -------------------- Blouses (31-40) --------------------
  {
    id: 31,
    name: "White Silk Blouse",
    category: "Blouses",
    price: 69.99,
    currency: "GHS",
    image: "/images/blouses/white-blouse.jpg",
    description: "Elegant silk blouse",
    inStock: true,
  },
  {
    id: 32,
    name: "Pastel Pink Blouse",
    category: "Blouses",
    price: 64.99,
    currency: "GHS",
    image: "/images/blouses/pink-blouse.jpg",
    description: "Soft pastel blouse",
    inStock: true,
  },
  {
    id: 33,
    name: "Blue Button Blouse",
    category: "Blouses",
    price: 66.99,
    currency: "GHS",
    image: "/images/blouses/blue-blouse.jpg",
    description: "Professional button blouse",
    inStock: false,
  },
  {
    id: 34,
    name: "Grey Wrap Blouse",
    category: "Blouses",
    price: 68.99,
    currency: "GHS",
    image: "/images/blouses/grey-blouse.jpg",
    description: "Modern grey wrap blouse",
    inStock: true,
  },
  {
    id: 35,
    name: "Lavender Work Blouse",
    category: "Blouses",
    price: 65.99,
    currency: "GHS",
    image: "/images/blouses/lavender-blouse.jpg",
    description: "Light lavender professional blouse",
    inStock: true,
  },
  {
    id: 36,
    name: "Beige Office Blouse",
    category: "Blouses",
    price: 63.99,
    currency: "GHS",
    image: "/images/blouses/beige-blouse.jpg",
    description: "Beige blouse suitable for office",
    inStock: true,
  },
  {
    id: 37,
    name: "White Lace Blouse",
    category: "Blouses",
    price: 70.99,
    currency: "GHS",
    image: "/images/blouses/lace-blouse.jpg",
    description: "Elegant lace blouse",
    inStock: false,
  },
  {
    id: 38,
    name: "Black Formal Blouse",
    category: "Blouses",
    price: 68.99,
    currency: "GHS",
    image: "/images/blouses/black-blouse.jpg",
    description: "Classic black office blouse",
    inStock: true,
  },
  {
    id: 39,
    name: "Mint Green Blouse",
    category: "Blouses",
    price: 66.99,
    currency: "GHS",
    image: "/images/blouses/mint-blouse.jpg",
    description: "Fresh mint color blouse",
    inStock: true,
  },
  {
    id: 40,
    name: "Light Blue Wrap Blouse",
    category: "Blouses",
    price: 65.99,
    currency: "GHS",
    image: "/images/blouses/lightblue-blouse.jpg",
    description: "Professional wrap blouse",
    inStock: true,
  },

  // -------------------- Skirts (41-50) --------------------
  {
    id: 41,
    name: "Black Pencil Skirt",
    category: "Skirts",
    price: 49.99,
    currency: "GHS",
    image: "/images/skirts/black-pencil.jpg",
    description: "Classic pencil skirt for office wear",
    inStock: true,
  },
  {
    id: 42,
    name: "Grey A-Line Skirt",
    category: "Skirts",
    price: 44.99,
    currency: "GHS",
    image: "/images/skirts/grey-a-line.jpg",
    description: "Comfortable A-line skirt for professional settings",
    inStock: true,
  },
  {
    id: 43,
    name: "Navy Office Skirt",
    category: "Skirts",
    price: 45.99,
    currency: "GHS",
    image: "/images/skirts/navy-skirt.jpg",
    description: "Formal navy skirt",
    inStock: false,
  },
  {
    id: 44,
    name: "Black Wrap Skirt",
    category: "Skirts",
    price: 47.99,
    currency: "GHS",
    image: "/images/skirts/black-wrap.jpg",
    description: "Modern wrap skirt",
    inStock: true,
  },
  {
    id: 45,
    name: "Beige Pleated Skirt",
    category: "Skirts",
    price: 46.99,
    currency: "GHS",
    image: "/images/skirts/beige-pleated.jpg",
    description: "Elegant pleated office skirt",
    inStock: true,
  },
  {
    id: 46,
    name: "Charcoal Midi Skirt",
    category: "Skirts",
    price: 48.99,
    currency: "GHS",
    image: "/images/skirts/charcoal-midi.jpg",
    description: "Midi skirt for professional look",
    inStock: true,
  },
  {
    id: 47,
    name: "Light Grey Pencil Skirt",
    category: "Skirts",
    price: 44.99,
    currency: "GHS",
    image: "/images/skirts/lightgrey-pencil.jpg",
    description: "Classic pencil skirt",
    inStock: true,
  },
  {
    id: 48,
    name: "Black Flared Skirt",
    category: "Skirts",
    price: 46.99,
    currency: "GHS",
    image: "/images/skirts/black-flared.jpg",
    description: "Professional flared skirt",
    inStock: false,
  },
  {
    id: 49,
    name: "Navy Pleated Skirt",
    category: "Skirts",
    price: 45.99,
    currency: "GHS",
    image: "/images/skirts/navy-pleated.jpg",
    description: "Pleated skirt for office",
    inStock: true,
  },
  {
    id: 50,
    name: "Grey Work Skirt",
    category: "Skirts",
    price: 47.99,
    currency: "GHS",
    image: "/images/skirts/grey-work.jpg",
    description: "Stylish grey skirt",
    inStock: true,
  },

  // -------------------- Dresses (51-60) --------------------
  {
    id: 51,
    name: "Navy Work Dress",
    category: "Dresses",
    price: 79.99,
    currency: "GHS",
    image: "/images/dresses/navy-dress.jpg",
    description: "Professional navy dress",
    inStock: true,
  },
  {
    id: 52,
    name: "Black Sheath Dress",
    category: "Dresses",
    price: 84.99,
    currency: "GHS",
    image: "/images/dresses/black-sheath.jpg",
    description: "Elegant sheath dress for office",
    inStock: true,
  },
  {
    id: 53,
    name: "Grey Midi Dress",
    category: "Dresses",
    price: 77.99,
    currency: "GHS",
    image: "/images/dresses/grey-midi.jpg",
    description: "Comfortable office dress",
    inStock: false,
  },
  {
    id: 54,
    name: "Pastel Pink Dress",
    category: "Dresses",
    price: 75.99,
    currency: "GHS",
    image: "/images/dresses/pink-dress.jpg",
    description: "Soft pink professional dress",
    inStock: true,
  },
  {
    id: 55,
    name: "Black Wrap Dress",
    category: "Dresses",
    price: 82.99,
    currency: "GHS",
    image: "/images/dresses/black-wrap.jpg",
    description: "Modern wrap office dress",
    inStock: true,
  },
  {
    id: 56,
    name: "Navy Shift Dress",
    category: "Dresses",
    price: 78.99,
    currency: "GHS",
    image: "/images/dresses/navy-shift.jpg",
    description: "Elegant shift dress",
    inStock: true,
  },
  {
    id: 57,
    name: "Grey Sheath Dress",
    category: "Dresses",
    price: 79.99,
    currency: "GHS",
    image: "/images/dresses/grey-sheath.jpg",
    description: "Professional sheath dress",
    inStock: true,
  },
  {
    id: 58,
    name: "Beige Midi Dress",
    category: "Dresses",
    price: 76.99,
    currency: "GHS",
    image: "/images/dresses/beige-midi.jpg",
    description: "Comfortable office dress",
    inStock: false,
  },
  {
    id: 59,
    name: "Black Pencil Dress",
    category: "Dresses",
    price: 83.99,
    currency: "GHS",
    image: "/images/dresses/black-pencil.jpg",
    description: "Elegant pencil dress",
    inStock: true,
  },
  {
    id: 60,
    name: "Blue Work Dress",
    category: "Dresses",
    price: 80.99,
    currency: "GHS",
    image: "/images/dresses/blue-work.jpg",
    description: "Professional blue office dress",
    inStock: true,
  },

  // -------------------- Footwear (61-75) --------------------
  {
    id: 61,
    name: "Men's Black Oxford Shoes",
    category: "Footwear",
    price: 99.99,
    currency: "GHS",
    image: "/images/footwear/mens-black-oxford.jpg",
    description: "Classic leather shoes for business",
    inStock: true,
  },
  {
    id: 62,
    name: "Men's Brown Dress Shoes",
    category: "Footwear",
    price: 95.99,
    currency: "GHS",
    image: "/images/footwear/mens-brown.jpg",
    description: "Elegant brown shoes",
    inStock: true,
  },
  {
    id: 63,
    name: "Men's Black Loafers",
    category: "Footwear",
    price: 89.99,
    currency: "GHS",
    image: "/images/footwear/mens-loafers.jpg",
    description: "Comfortable black loafers",
    inStock: false,
  },
  {
    id: 64,
    name: "Women's Black Heels",
    category: "Footwear",
    price: 89.99,
    currency: "GHS",
    image: "/images/footwear/womens-black-heels.jpg",
    description: "Elegant heels suitable for office",
    inStock: true,
  },
  {
    id: 65,
    name: "Women's Nude Pumps",
    category: "Footwear",
    price: 84.99,
    currency: "GHS",
    image: "/images/footwear/womens-nude.jpg",
    description: "Professional nude pumps",
    inStock: true,
  },
  {
    id: 66,
    name: "Women's Black Flats",
    category: "Footwear",
    price: 79.99,
    currency: "GHS",
    image: "/images/footwear/womens-flats.jpg",
    description: "Comfortable office flats",
    inStock: true,
  },
  {
    id: 67,
    name: "Men's Navy Loafers",
    category: "Footwear",
    price: 92.99,
    currency: "GHS",
    image: "/images/footwear/mens-navy.jpg",
    description: "Stylish loafers for office",
    inStock: true,
  },
  {
    id: 68,
    name: "Women's Burgundy Heels",
    category: "Footwear",
    price: 88.99,
    currency: "GHS",
    image: "/images/footwear/womens-burgundy.jpg",
    description: "Elegant office heels",
    inStock: false,
  },
  {
    id: 69,
    name: "Men's Grey Dress Shoes",
    category: "Footwear",
    price: 94.99,
    currency: "GHS",
    image: "/images/footwear/mens-grey.jpg",
    description: "Stylish grey leather shoes",
    inStock: true,
  },
  {
    id: 70,
    name: "Women's Navy Flats",
    category: "Footwear",
    price: 78.99,
    currency: "GHS",
    image: "/images/footwear/womens-navy-flats.jpg",
    description: "Comfortable flats for office",
    inStock: true,
  },
  {
    id: 71,
    name: "Men's Tan Loafers",
    category: "Footwear",
    price: 91.99,
    currency: "GHS",
    image: "/images/footwear/mens-tan-loafers.jpg",
    description: "Smart casual loafers",
    inStock: true,
  },
  {
    id: 72,
    name: "Women's Grey Pumps",
    category: "Footwear",
    price: 85.99,
    currency: "GHS",
    image: "/images/footwear/womens-grey-pumps.jpg",
    description: "Elegant grey pumps",
    inStock: true,
  },
  {
    id: 73,
    name: "Men's Black Monk Strap",
    category: "Footwear",
    price: 97.99,
    currency: "GHS",
    image: "/images/footwear/mens-monk.jpg",
    description: "Stylish monk strap shoes",
    inStock: false,
  },
  {
    id: 74,
    name: "Women's Beige Flats",
    category: "Footwear",
    price: 79.99,
    currency: "GHS",
    image: "/images/footwear/womens-beige-flats.jpg",
    description: "Comfortable office flats",
    inStock: true,
  },
  {
    id: 75,
    name: "Men's Dark Brown Oxford",
    category: "Footwear",
    price: 96.99,
    currency: "GHS",
    image: "/images/footwear/mens-dark-brown.jpg",
    description: "Classic brown Oxford shoes",
    inStock: true,
  },

  // -------------------- Accessories (76-85) --------------------
  {
    id: 76,
    name: "Black Leather Belt",
    category: "Accessories",
    price: 29.99,
    currency: "GHS",
    image: "/images/accessories/black-belt.jpg",
    description: "Classic leather belt",
    inStock: true,
  },
  {
    id: 77,
    name: "Brown Leather Belt",
    category: "Accessories",
    price: 28.99,
    currency: "GHS",
    image: "/images/accessories/brown-belt.jpg",
    description: "Elegant brown belt",
    inStock: true,
  },
  {
    id: 78,
    name: "Silk Tie - Navy",
    category: "Accessories",
    price: 24.99,
    currency: "GHS",
    image: "/images/accessories/navy-tie.jpg",
    description: "Professional silk tie",
    inStock: true,
  },
  {
    id: 79,
    name: "Silk Tie - Red",
    category: "Accessories",
    price: 24.99,
    currency: "GHS",
    image: "/images/accessories/red-tie.jpg",
    description: "Classic red silk tie",
    inStock: false,
  },
  {
    id: 80,
    name: "Leather Briefcase",
    category: "Accessories",
    price: 149.99,
    currency: "GHS",
    image: "/images/accessories/briefcase.jpg",
    description: "Professional leather briefcase",
    inStock: true,
  },
  {
    id: 81,
    name: "Black Leather Watch",
    category: "Accessories",
    price: 199.99,
    currency: "GHS",
    image: "/images/accessories/black-watch.jpg",
    description: "Elegant leather strap watch",
    inStock: true,
  },
  {
    id: 82,
    name: "Silver Cufflinks",
    category: "Accessories",
    price: 34.99,
    currency: "GHS",
    image: "/images/accessories/cufflinks.jpg",
    description: "Classic silver cufflinks",
    inStock: true,
  },
  {
    id: 83,
    name: "Women’s Leather Handbag",
    category: "Accessories",
    price: 129.99,
    currency: "GHS",
    image: "/images/accessories/handbag.jpg",
    description: "Professional leather handbag",
    inStock: true,
  },
  {
    id: 84,
    name: "Black Scarf",
    category: "Accessories",
    price: 39.99,
    currency: "GHS",
    image: "/images/accessories/black-scarf.jpg",
    description: "Soft office scarf",
    inStock: false,
  },
  {
    id: 85,
    name: "Brown Gloves",
    category: "Accessories",
    price: 49.99,
    currency: "GHS",
    image: "/images/accessories/brown-gloves.jpg",
    description: "Elegant leather gloves",
    inStock: true,
  },

  // -------------------- Outerwear (86-100) --------------------
  {
    id: 86,
    name: "Black Blazer",
    category: "Outerwear",
    price: 129.99,
    currency: "GHS",
    image: "/images/outerwear/black-blazer.jpg",
    description: "Formal black blazer",
    inStock: true,
  },
  {
    id: 87,
    name: "Navy Blazer",
    category: "Outerwear",
    price: 135.99,
    currency: "GHS",
    image: "/images/outerwear/navy-blazer.jpg",
    description: "Professional navy blazer",
    inStock: true,
  },
  {
    id: 88,
    name: "Grey Blazer",
    category: "Outerwear",
    price: 132.99,
    currency: "GHS",
    image: "/images/outerwear/grey-blazer.jpg",
    description: "Classic grey blazer",
    inStock: true,
  },
  {
    id: 89,
    name: "Black Trench Coat",
    category: "Outerwear",
    price: 149.99,
    currency: "GHS",
    image: "/images/outerwear/black-trench.jpg",
    description: "Elegant black trench coat",
    inStock: false,
  },
  {
    id: 90,
    name: "Grey Wool Coat",
    category: "Outerwear",
    price: 159.99,
    currency: "GHS",
    image: "/images/outerwear/grey-wool.jpg",
    description: "Warm wool coat",
    inStock: true,
  },
  {
    id: 91,
    name: "Navy Overcoat",
    category: "Outerwear",
    price: 162.99,
    currency: "GHS",
    image: "/images/outerwear/navy-overcoat.jpg",
    description: "Professional navy overcoat",
    inStock: true,
  },
  {
    id: 92,
    name: "Beige Coat",
    category: "Outerwear",
    price: 155.99,
    currency: "GHS",
    image: "/images/outerwear/beige-coat.jpg",
    description: "Light beige coat for office",
    inStock: true,
  },
  {
    id: 93,
    name: "Black Leather Jacket",
    category: "Outerwear",
    price: 175.99,
    currency: "GHS",
    image: "/images/outerwear/black-jacket.jpg",
    description: "Stylish leather jacket",
    inStock: true,
  },
  {
    id: 94,
    name: "Grey Blazer with Pockets",
    category: "Outerwear",
    price: 134.99,
    currency: "GHS",
    image: "/images/outerwear/grey-pockets.jpg",
    description: "Grey blazer with front pockets",
    inStock: true,
  },
  {
    id: 95,
    name: "Women's Navy Coat",
    category: "Outerwear",
    price: 158.99,
    currency: "GHS",
    image: "/images/outerwear/womens-navy.jpg",
    description: "Elegant navy coat for women",
    inStock: true,
  },
  {
    id: 96,
    name: "Women's Beige Blazer",
    category: "Outerwear",
    price: 140.99,
    currency: "GHS",
    image: "/images/outerwear/womens-beige.jpg",
    description: "Professional beige blazer",
    inStock: true,
  },
  {
    id: 97,
    name: "Men’s Charcoal Coat",
    category: "Outerwear",
    price: 160.99,
    currency: "GHS",
    image: "/images/outerwear/mens-charcoal.jpg",
    description: "Elegant charcoal coat for men",
    inStock: false,
  },
  {
    id: 98,
    name: "Women's Black Coat",
    category: "Outerwear",
    price: 162.99,
    currency: "GHS",
    image: "/images/outerwear/womens-black.jpg",
    description: "Professional black coat",
    inStock: true,
  },
  {
    id: 99,
    name: "Grey Wool Blazer",
    category: "Outerwear",
    price: 138.99,
    currency: "GHS",
    image: "/images/outerwear/grey-wool-blazer.jpg",
    description: "Warm wool blazer",
    inStock: true,
  },
  {
    id: 100,
    name: "Men’s Navy Trench Coat",
    category: "Outerwear",
    price: 165.99,
    currency: "GHS",
    image: "/images/outerwear/mens-navy-trench.jpg",
    description: "Elegant navy trench coat",
    inStock: true,
  },
]
